# tasks file for simulatedwebcam
- name: Install Webcam Tools
  ansible.builtin.apt:
    pkg: "{{simulatedwebcam_tools}}"
    state: present
  tags: [install]
  become: true

- name: Copy webcam simulation video
  ansible.builtin.copy:
    src: webcamsimulation.mp4
    dest: "{{simulatedwebcam_video}}"
    owner: root
    group: root
    mode: 0644
  become: true

- name: Create ffmpeg service
  ansible.builtin.template:
    src: ffmpeg.service.j2
    dest: /lib/systemd/system/ffmpeg.service
    owner: root
    group: root
    mode: 0644

- name: Start ffmpeg service
  systemd:
    name: ffmpeg
    state: started
    enabled: true
