#!/usr/bin/env python3

import socket
from sys import argv

target_port = 1881

if len(argv) < 3 or len(argv) > 4 :
    print(f"usage: {argv[0]} <host> <status> [<port>]")
    exit(1)

target_host = argv[1]

if len(argv) == 4:
    target_port = argv[3]

host = socket.gethostname().encode() + b'\r\n'
status = argv[2].encode() + b'\r\n'

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((target_host, target_port))
    data = s.recv(1024)
    s.sendall(host)
    data = s.recv(1024)
    s.sendall(status)

exit(0)
