#SPDX-License-Identifier: MIT-0
---
# tasks file for dockerce
- name: Remove docker-related packages
  ansible.builtin.apt:
    pkg:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
  tags:
    - install

- name: Install repository dependencies
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
    update_cache: yes
  tags:
    - install

- name: Create a keyring-directory if it does not exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
    - install

- name: Download docker-keys
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0444'
  tags:
    - install

- name: Add specified docker repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present
  tags:
    - install

- name: Install docker-ce packages
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  tags:
    - install
